### ISSUE TITLE
Chromedriver文件放在哪啊？

### ISSUE THREAD

**Issue by jiando** [linyuli861/Automated-Test#1]
ft1.1: Traceback (most recent call last):
  File "C:\Users\roben\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\roben\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\roben\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\Python\AutoTest\testcase\test_baiduSearch.py", line 12, in setUp
    self.driver = webdriver.Chrome()
  File "C:\Users\roben\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\roben\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by lilinyu861** [comment]
chromedriver是你本机上配置的，一般放置在C:\Program Files (x86)\Google\Chrome\Application文件夹中，并加入PATH环境变量。
如果您已进行上面的操作，可查看[](https://blog.csdn.net/qq_31524409/article/details/88422148)尝试解决。

**Comment by artest7** [comment]
![image](https://user-images.githubusercontent.com/42361900/60975936-58e2f400-a35f-11e9-8247-8daeb16cc377.png)
![image](https://user-images.githubusercontent.com/42361900/60976022-8334b180-a35f-11e9-8a76-6d731de4aca2.png)

非常感谢你的回复！只是文件我加了，环境变量也配置了，还是没用..

**Comment by lilinyu861** [comment]
你可以查看https://blog.csdn.net/qq_31524409/article/details/88422148 尝试解决一下。

**Comment by artest7** [comment]
> 你可以查看https://blog.csdn.net/qq_31524409/article/details/88422148 尝试解决一下。

可以了，太感谢你了！

**Comment by lilinyu861** [comment]
不客气
